### PR TITLE
Pin the cross binary to avoid CI flakiness

### PR DESCRIPTION
**Pull request by josephlr**
Signed-off-by: Joe Richey <joerichey@google.com>

### CODE REVIEW

**Comment by josephlr** [comment]
@dhardy this is ready to merge and should fix some if the flakiness I saw in #146

**Comment by dhardy** [comment]
Both the Linux runners seem to be happy.

Any idea what happened to AppVeyor? It [hasn't run in a month](https://ci.appveyor.com/project/rust-random/getrandom/history).

**Comment by josephlr** [comment]
> Both the Linux runners seem to be happy.

It's weird, I saw `cross` related failures [here](https://travis-ci.org/github/rust-random/getrandom/jobs/690219181), but then I re-ran things and everything worked. I think the issue was causes by some things getting out of sync right when [a new version of `cross` was released](https://github.com/rust-embedded/cross/releases/tag/v0.2.0). Regardless, pinning should prevent this sort of thing.

> Any idea what happened to AppVeyor? It [hasn't run in a month](https://ci.appveyor.com/project/rust-random/getrandom/history).

I'll see what happens when I merge this PR, maybe it's only running on `master`?

**Comment by josephlr** [comment]
> > Any idea what happened to AppVeyor? It [hasn't run in a month](https://ci.appveyor.com/project/rust-random/getrandom/history).
> 
> I'll see what happens when I merge this PR, maybe it's only running on `master`?

It looks like AppVeyor just wasn't running on the 0.2 branch, #148 fixes that issue

**Pull request merged**
