### PR TITLE
Update 0.1 branch to use Github actions

### PR DESCRIPTION
**Pull request by josephlr**
Also update the badges in the README

Signed-off-by: Joe Richey <joerichey@google.com>

### CODE REVIEW

**Review by newpavlov — APPROVED** [review]
Maybe it's worth to simply remove the commented out lines in the workflow config?

**Comment by josephlr** [comment]
> Maybe it's worth to simply remove the commented out lines in the workflow config?

Ya, I'm just going to copy over the config from #192 and see if I can just use that.

**Comment by josephlr** [comment]
Ok @newpavlov, this is now just a slightly modified version of the config in #192, and all 34 of the jobs are now passing. So once you approve that one, I'll merge this one.

**Review by newpavlov — APPROVED** [review]
I left some minor comments in #192 which apply here as well, but otherwise looks good!

**Comment by josephlr** [comment]
> I left some minor comments in #192 which apply here as well, but otherwise looks good!

Applied the fixed from #192 to this branch

**Pull request merged**
