### PR TITLE
Backport update to cfg-if v1.0 to the v0.1 branch

### PR DESCRIPTION
**Pull request by newpavlov**
Requested in #166.

### CODE REVIEW

**Comment by Dragonrun1** [comment]
So this is now the only part of rand crates that is still using the old version of cfg-if. Do we have a timeline when this is getting merged?

**Comment by newpavlov** [comment]
@Dragonrun1
It's blocked on @josephlr approving this PR.

**Comment by Dragonrun1** [comment]
Actually I just updated to rand 0.8 and was looking with `cargo tree` and noticed it showing this package still using the old version. If you look at the Cargo.toml on getrandom it still shows `cfg-if = "0.1.2"` so that kind of why I decided to ask 😉

**Review by josephlr — APPROVED** [review]
Sorry for letting this slip by. Thanks for the backport!

**Pull request merged**
