### PR TITLE
Support random file of AIX

### PR DESCRIPTION
**Pull request by ecnelises**

### CODE REVIEW

**Comment by josephlr** [comment]
Could we add some IBM docs to justify the implementation choice? I think this is correct, but I've never worked with AIX

**Comment by ecnelises** [comment]
The official doc can be found at https://www.ibm.com/docs/en/aix/7.2?topic=files-random-urandom-devices , [this discussion in GnuPG mailing list](https://lists.gnupg.org/pipermail/gnupg-devel/2003-April/019954.html) is also good reference.

In short, the mechanism of `/dev/urandom` (and `/dev/random`) on AIX is the same as [Linux](https://unix.stackexchange.com/questions/324209/when-to-use-dev-random-vs-dev-urandom): the former is more reliable (it never blocks).

**Comment by josephlr** [comment]
@ecnelises I'm just wondering if we will have to `poll` `/dev/random` like we do on Linux. I don't think we have to, but I'd like to see what OpenSSL does.

**Comment by ecnelises** [comment]
> @ecnelises I'm just wondering if we will have to `poll` `/dev/random` like we do on Linux. I don't think we have to, but I'd like to see what OpenSSL does.

According to [rand_unix.c](https://github.com/openssl/openssl/blob/master/providers/implementations/rands/seeding/rand_unix.c) in OpenSSL, only Linux defines `DEVRANDOM_WAIT`, and `/dev/urandom` is in the highest priority by default.

**Comment by josephlr** [comment]
Can you add a row to the documentation in `lib.rs` about AIX (and link to the official IBM docs).

I think we should also add AIX to the Tier 3 section of our CI. That may require waiting on Rust Nightly to actually understand the target.

**Comment by josephlr** [comment]
Note: we are blocked on https://github.com/rust-lang/rust/pull/102293 being merged.

**Comment by ecnelises** [comment]
That PR has been merged :)

**Review by newpavlov — APPROVED** [review]

**Pull request merged**
