### PR TITLE
Fix Redox CI

### LINKED ISSUE #79: Redox support
https://github.com/rust-random/getrandom/blob/199b11576eea7aab93a0162e36571b8b607f0000/.travis.yml#L105

Since https://github.com/rust-lang/rust/issues/60139 is still open, we probably don't want to do anything about this yet. In this case however we also need to disable rand tests ([see this failure](https://travis-ci.org/rust-random/rand/jobs/567814932)).

### PR DESCRIPTION
**Pull request by josephlr**
Fixes #79

### CODE REVIEW

**Comment by newpavlov** [comment]
Hopefully rust-lang/rust#63521 will land soon and we will not have to use `xbuild` for Redox.

**Comment by newpavlov** [comment]
@josephlr 
Can you revert to the old `cargo build`? The builder PR has landed, so we should get pre-built Redox `std` soon.

**Comment by josephlr** [comment]
@newpavlov will do. Looks like redox is now back to building in the latest nightly.
https://rust-lang.github.io/rustup-components-history/x86_64-unknown-redox.html

**Comment by newpavlov** [comment]
Argh, looks like `libc` is still broken on Redox...

**Comment by josephlr** [comment]
> Argh, looks like `libc` is still broken on Redox...

I confirmed locally that 0.2.62 seems to fix things. So this can be merged once the CI passes.

**Comment by josephlr** [comment]
Whoops @newpavlov, I thought you had approved this, so I merged it. We should probably enable the feature that requires review before merging. Would that work for you?

**Comment by newpavlov** [comment]
Yeah, no problem. I am not sure if we need this setting, but either way, I think we will need @dhardy for that.

**Comment by dhardy** [comment]
Done

**Pull request merged**
