### PR TITLE
Added x86_64-unknown-hermit support

### PR DESCRIPTION
**Pull request by sjmackenzie**
[Later](https://github.com/hermitcore/rusty-hermit/pull/64#issuecomment-980668685) once hermit supports `aarch64` rng I'll make a patch to support it. 

For more context see #199

### CODE REVIEW

**Review by newpavlov — APPROVED** [review]
Hm, I would prefer a proper buffer-based API, but I guess this code should be a fine stop-gap solution.

I will leave this PR open for some time in the case if @josephlr has any concerns.

Meanwhile can you please add an `[UNRELEASED]` section to the changelog with an entry containing description of this PR? Also it would be nice to add a Hermit build test to the CI workflow.

**Comment by sjmackenzie** [comment]
Agreed on the buffer-based API, I suggest this is good feedback for @stlankes & @josephlr!

I believe `getrandom` CI already has hermit workflow support, correct me if I'm wrong please: https://github.com/rust-random/getrandom/blob/f5e33009edc2ac5ea59f7dde68709e9572b94458/.github/workflows/tests.yml#L312

Ideally I'd love to try get this stop-gap merged relatively soon as there are a number of transitive dependencies I need to lobby to bump to a hermit-supported-getrandom. I'm choosing hermit as the sole target platform for an existing project. 

@josephlr I'd love your feedback on this stop-gap solution.

@newpavlov I'd pushed the requested changes, if you could be so kind and review them.

Thanks!

**Comment by sjmackenzie** [comment]
By buffer-based API do you mean you can pass in an arbitrary sized `u8` buffer and it'd be filled accordingly? If so, this is what is happening in this PR.

**Comment by newpavlov** [comment]
>By buffer-based API do you mean you can pass in an arbitrary sized u8 buffer and it'd be filled accordingly? If so, this is what is happening in this PR.

I meant a "syscall" on the Hermit side, like requested in https://github.com/hermitcore/libhermit-rs/issues/143 

>I believe getrandom CI already has hermit workflow support, correct me if I'm wrong please:

Ah, I forgot about that. You can simply remove the `--features=rdrand` part then since it's not longer needed.

**Comment by sjmackenzie** [comment]
Thanks for removing the `--features=rdrand`, it fell on the wayside. Appreciate the merge!

**Pull request merged**
