### PR TITLE
Run Rustfmt on entire repo

### PR DESCRIPTION
**Pull request by josephlr**
This PR keeps `allow_failures` in the Travis presubmit, we should just run rustfmt from time to time.

### CODE REVIEW

**Comment by newpavlov** [comment]
Personally I am not sure about removing `allow_failures`, in my experience it results in a more annoyance than it's worth.

**Comment by josephlr** [comment]
> Personally I am not sure about removing allow_failures, in my experience it results in a more annoyance than it's worth.

I mean all it does is force PRs to be properly formatted when they are submitted. Or is it more a concern about `rustfmt`'s stability?

**Comment by newpavlov** [comment]
Both, I had experienced CI breakage on my projects due to `rustfmt` changes, and it will be annoying for contributors who don't use `rustfmt`.

**Comment by josephlr** [comment]
@newpavlov that makes sense, fixed

**Pull request merged**
