### PR TITLE
Prepare 0.1.1 release

### PR DESCRIPTION
**Pull request by dhardy**

### CODE REVIEW

**Comment by newpavlov** [comment]
I wouldn't say it's a "fix", I would write something like "enable std functionality for CloudABI by default".

Also how about adding zero buffer test in this PR as well?

**Comment by dhardy** [comment]
Oh, sure. Shall I close this and let you do that?

**Comment by newpavlov** [comment]
I think you can simply add the test as part of this PR.

**Comment by dhardy** [comment]
Okay, I will do it.

**Pull request merged**
